// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AuthGetStatus() {
  return window['go']['main']['App']['AuthGetStatus']();
}

export function AuthSignIn() {
  return window['go']['main']['App']['AuthSignIn']();
}

export function AuthSignOut() {
  return window['go']['main']['App']['AuthSignOut']();
}
