// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {events} from '../models';
import {main} from '../models';
import {drive} from '../models';

export function AuthGetStatus():Promise<events.AuthStatus>;

export function AuthSignIn():Promise<events.AuthStatus>;

export function AuthSignOut():Promise<void>;

export function CaptionsAnswerModelDownload(arg1:boolean):Promise<main.CaptionSettingsDTO>;

export function CaptionsGetJob(arg1:number):Promise<events.CaptionJob>;

export function CaptionsGetSettings():Promise<main.CaptionSettingsDTO>;

export function CaptionsSetEnabled(arg1:boolean):Promise<main.CaptionSettingsDTO>;

export function CaptionsSetLanguage(arg1:string):Promise<main.CaptionSettingsDTO>;

export function CaptionsShowLocalCopy(arg1:number):Promise<void>;

export function DebugRestart():Promise<void>;

export function DebugSessionReleaseCount():Promise<number>;

export function DriveGetStorageQuota():Promise<drive.StorageQuota>;

export function DriveListFolders(arg1:string):Promise<Array<drive.Folder>>;

export function FilesPickLocal():Promise<main.LocalFileRef>;

export function FilesPickLocalMultiple():Promise<Array<main.LocalFileRef>>;

export function SummariesAnswerModelDownload(arg1:boolean):Promise<main.SummarySettingsDTO>;

export function SummariesGetJob(arg1:number):Promise<events.SummaryJob>;

export function SummariesGetSettings():Promise<main.SummarySettingsDTO>;

export function SummariesRetry(arg1:number):Promise<events.SummaryJob>;

export function SummariesSetEnabled(arg1:boolean):Promise<main.SummarySettingsDTO>;

export function SummariesShowLocalCopy(arg1:number):Promise<void>;

export function UploadCancel(arg1:number):Promise<void>;

export function UploadConfirmRestart(arg1:number):Promise<void>;

export function UploadDelete(arg1:number):Promise<void>;

export function UploadGetRecoverable():Promise<main.RecoverableUploadDTO>;

export function UploadGetStatus(arg1:number):Promise<main.UploadStatusDTO>;

export function UploadListRecent():Promise<Array<main.UploadListItemDTO>>;

export function UploadRetry(arg1:number):Promise<number>;

export function UploadStart(arg1:string,arg2:string,arg3:string):Promise<number>;
