// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {events} from '../models';
import {drive} from '../models';
import {main} from '../models';

export function AuthGetStatus():Promise<events.AuthStatus>;

export function AuthSignIn():Promise<events.AuthStatus>;

export function AuthSignOut():Promise<void>;

export function DebugRestart():Promise<void>;

export function DriveListFolders(arg1:string):Promise<Array<drive.Folder>>;

export function FilesPickLocal():Promise<main.LocalFileRef>;

export function UploadCancel(arg1:number):Promise<void>;

export function UploadConfirmRestart(arg1:number):Promise<void>;

export function UploadGetRecoverable():Promise<main.RecoverableUploadDTO>;

export function UploadGetStatus(arg1:number):Promise<main.UploadStatusDTO>;

export function UploadStart(arg1:string,arg2:string):Promise<number>;
