// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AuthGetStatus() {
  return window['go']['main']['App']['AuthGetStatus']();
}

export function AuthSignIn() {
  return window['go']['main']['App']['AuthSignIn']();
}

export function AuthSignOut() {
  return window['go']['main']['App']['AuthSignOut']();
}

export function DriveListFolders(arg1) {
  return window['go']['main']['App']['DriveListFolders'](arg1);
}

export function FilesPickLocal() {
  return window['go']['main']['App']['FilesPickLocal']();
}

export function UploadGetStatus(arg1) {
  return window['go']['main']['App']['UploadGetStatus'](arg1);
}

export function UploadStart(arg1, arg2) {
  return window['go']['main']['App']['UploadStart'](arg1, arg2);
}
