// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AuthGetStatus() {
  return window['go']['main']['App']['AuthGetStatus']();
}

export function AuthSignIn() {
  return window['go']['main']['App']['AuthSignIn']();
}

export function AuthSignOut() {
  return window['go']['main']['App']['AuthSignOut']();
}

export function CaptionsAnswerModelDownload(arg1) {
  return window['go']['main']['App']['CaptionsAnswerModelDownload'](arg1);
}

export function CaptionsGetJob(arg1) {
  return window['go']['main']['App']['CaptionsGetJob'](arg1);
}

export function CaptionsGetSettings() {
  return window['go']['main']['App']['CaptionsGetSettings']();
}

export function CaptionsSetEnabled(arg1) {
  return window['go']['main']['App']['CaptionsSetEnabled'](arg1);
}

export function CaptionsSetLanguage(arg1) {
  return window['go']['main']['App']['CaptionsSetLanguage'](arg1);
}

export function CaptionsShowLocalCopy(arg1) {
  return window['go']['main']['App']['CaptionsShowLocalCopy'](arg1);
}

export function DebugRestart() {
  return window['go']['main']['App']['DebugRestart']();
}

export function DebugSessionReleaseCount() {
  return window['go']['main']['App']['DebugSessionReleaseCount']();
}

export function DriveGetStorageQuota() {
  return window['go']['main']['App']['DriveGetStorageQuota']();
}

export function DriveListFolders(arg1) {
  return window['go']['main']['App']['DriveListFolders'](arg1);
}

export function FilesPickLocal() {
  return window['go']['main']['App']['FilesPickLocal']();
}

export function FilesPickLocalMultiple() {
  return window['go']['main']['App']['FilesPickLocalMultiple']();
}

export function SummariesAnswerModelDownload(arg1) {
  return window['go']['main']['App']['SummariesAnswerModelDownload'](arg1);
}

export function SummariesGetJob(arg1) {
  return window['go']['main']['App']['SummariesGetJob'](arg1);
}

export function SummariesGetSettings() {
  return window['go']['main']['App']['SummariesGetSettings']();
}

export function SummariesRetry(arg1) {
  return window['go']['main']['App']['SummariesRetry'](arg1);
}

export function SummariesSetEnabled(arg1) {
  return window['go']['main']['App']['SummariesSetEnabled'](arg1);
}

export function SummariesShowLocalCopy(arg1) {
  return window['go']['main']['App']['SummariesShowLocalCopy'](arg1);
}

export function UploadCancel(arg1) {
  return window['go']['main']['App']['UploadCancel'](arg1);
}

export function UploadConfirmRestart(arg1) {
  return window['go']['main']['App']['UploadConfirmRestart'](arg1);
}

export function UploadDelete(arg1) {
  return window['go']['main']['App']['UploadDelete'](arg1);
}

export function UploadGetRecoverable() {
  return window['go']['main']['App']['UploadGetRecoverable']();
}

export function UploadGetStatus(arg1) {
  return window['go']['main']['App']['UploadGetStatus'](arg1);
}

export function UploadListRecent() {
  return window['go']['main']['App']['UploadListRecent']();
}

export function UploadRetry(arg1) {
  return window['go']['main']['App']['UploadRetry'](arg1);
}

export function UploadStart(arg1, arg2, arg3) {
  return window['go']['main']['App']['UploadStart'](arg1, arg2, arg3);
}
