// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {events} from '../models';

export function AuthGetStatus():Promise<events.AuthStatus>;

export function AuthSignIn():Promise<events.AuthStatus>;

export function AuthSignOut():Promise<void>;
